### ISSUE TITLE
Colab 'Namespace' object has no attribute 'clip_models'` error

### ISSUE THREAD

**Issue by ndhuanhuan** [rinongal/StyleGAN-nada#4] opened 2021-08-10 22:44 UTC
`
   41 args = Namespace(**training_args)
     42 
---> 43 net = ZSSGAN(args)
     44 
     45 g_reg_ratio = 4 / 5
    /content/stylegan_nada/ZSSGAN/model/ZSSGAN.py in __init__(self, args)
          172                                                       lambda_texture=args.lambda_texture,
          173                                                       clip_model=model_name) 
      --> 174                                 for model_name in args.clip_models}
          175 
          176         self.clip_model_weights = {model_name: weight for model_name, weight in zip(args.clip_models, args.clip_model_weights)}
      AttributeError: 'Namespace' object has no attribute 'clip_models'`

While running sample colab notebook Step 3, this error happens. Is there any fix for this?

**Comment by xinformatics** [comment] 2021-08-11 00:48
I am facing this error too; using colab.

**Comment by rinongal** [comment] 2021-08-11 05:51
Can you verify that you're using our own colab, with [the link from the repo](https://colab.research.google.com/github/rinongal/stylegan-nada/blob/main/stylegan_nada.ipynb)? 

We had a pre-paper release version available for a few weeks which used a different set of arguments, and many of the derivative notebooks out there might still be based on that old version.

If the options in Step 3 don't look like the image below, you're not using an up-to-date notebook and that's probably the cause of the problem.

![image](https://user-images.githubusercontent.com/19426368/128976430-b18c4211-b3e1-4909-b137-ee2a37c9a015.png)

**Comment by xinformatics** [comment] 2021-08-11 13:50
Yes, I am using the notebook provided in the repo. Step3 is exactly same as you've shown in the image.

**Comment by rinongal** [comment] 2021-08-11 14:24
Could you please copy-paste the code block from step 3? Or better yet, save a copy of the notebook with the error and upload it here?

I'm having no luck reproducing this error in Colab, and I want to make sure it's not some notebook sync issue before I dive deeper.

![image](https://user-images.githubusercontent.com/19426368/129045175-613c1a3d-460e-49a7-b452-46b616181be4.png)

**Comment by ndhuanhuan** [comment] 2021-08-11 17:26
I cannot reproduce the error any more by using the latest Colab notebook.

**Comment by xinformatics** [comment] 2021-08-11 19:43
Its working fine now. Thank you for your help, you may close the issue.

**Closed** 2021-08-11 20:39 UTC
